### ISSUE TITLE
Running rails server

### ISSUE THREAD

**Issue by mtoribio** [graalvm/truffleruby#56] opened 2017-02-09 10:50 UTC
Hi,

I have a project in rails and I want to test how it run in graalvm.

- MACOS 10.12.2
- java version "1.8.0_111"
  Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
  Java HotSpot(TM) 64-Bit Server VM (build 25.71-b01-internal-jvmci-0.23, mixed mode)
- truffleruby SNAPSHOT, like ruby 2.3.1 <Java HotSpot(TM) 64-Bit Server VM 1.8.0_111-b14 with   Graal> [darwin-x86_64]

I already install bundle and gems follow:
https://github.com/graalvm/truffleruby/blob/master/doc/user/installing-gems.md
But when I try to exec rails server thats no works.
I tried:
- `ruby -S bundle exec bin/rails server`
```
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bson-4.2.1 because its extensions are not built.  Try: gem pristine bson --version 4.2.1
Ignoring byebug-9.0.6 because its extensions are not built.  Try: gem pristine byebug --version 9.0.6
Ignoring json-2.0.3 because its extensions are not built.  Try: gem pristine json --version 2.0.3
Ignoring nio4r-1.2.1 because its extensions are not built.  Try: gem pristine nio4r --version 1.2.1
Ignoring nokogiri-1.7.0.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.7.0.1
Ignoring plivo-0.3.11 because its extensions are not built.  Try: gem pristine plivo --version 0.3.11
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
Ignoring websocket-driver-0.6.5 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.5
bundler: command not found: bin/rails
Install missing gem executables with `bundle install`
```
- `ruby -S bundle exec rails server`
```
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bson-4.2.1 because its extensions are not built.  Try: gem pristine bson --version 4.2.1
Ignoring byebug-9.0.6 because its extensions are not built.  Try: gem pristine byebug --version 9.0.6
Ignoring json-2.0.3 because its extensions are not built.  Try: gem pristine json --version 2.0.3
Ignoring nio4r-1.2.1 because its extensions are not built.  Try: gem pristine nio4r --version 1.2.1
Ignoring nokogiri-1.7.0.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.7.0.1
Ignoring plivo-0.3.11 because its extensions are not built.  Try: gem pristine plivo --version 0.3.11
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
Ignoring websocket-driver-0.6.5 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.5
spawn_setup: close_others not yet implemented
Your bundle is locked to rake (12.0.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (12.0.0) has removed it. You'll need to update your bundle to a different version of rake (12.0.0) that hasn't been removed in order to install.
Run `bundle install` to install missing gems.
```

I hope to receive your reply soon,
Regards.

**Comment by forumd** [comment] 2017-02-09 11:07
I have been trying:
I set this env_var:
export PATH="$HOME/graalvm-0.20/language/ruby/lib/bin:$PATH"
```
because I found rails executable.
And now I have this error:
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bson-4.2.1 because its extensions are not built.  Try: gem pristine bson --version 4.2.1
Ignoring byebug-9.0.6 because its extensions are not built.  Try: gem pristine byebug --version 9.0.6
Ignoring json-2.0.3 because its extensions are not built.  Try: gem pristine json --version 2.0.3
Ignoring nio4r-1.2.1 because its extensions are not built.  Try: gem pristine nio4r --version 1.2.1
Ignoring nokogiri-1.7.0.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.7.0.1
Ignoring plivo-0.3.11 because its extensions are not built.  Try: gem pristine plivo --version 0.3.11
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
Ignoring websocket-driver-0.6.5 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.5
spawn_setup: close_others not yet implemented
env: truffleruby: No such file or directory
```

**Comment by eregon** [comment] 2017-02-09 12:30
Hello,
I believe part of these issues are caused by the environment variables `GEM_HOME`, `GEM_PATH` and `GEM_ROOT` being set and interfering with RubyGems/Bundler.

Could you try again by first switching to your system ruby:
`rvm use system` or `rbenv system` or `chruby system`?
I will document this in https://github.com/graalvm/truffleruby/blob/master/doc/user/installing-gems.md.

**Comment by Fudoshiki** [comment] 2017-03-04 12:50
same issue

**Comment by pitr-ch** [comment] 2017-03-05 10:46
@Fudoshiki Hi, what GraalVM are you using? If 0.20 try to fix with these steps: https://github.com/graalvm/truffleruby/blob/master/doc/user/ruby-managers.md. Or you could wait for 0.21 it will be more user friendly.

**Comment by Fudoshiki** [comment] 2017-03-05 17:55
@pitr-ch 0.20 with this steps. Waiting for 0.21

**Comment by Fudoshiki** [comment] 2017-03-14 21:20
macOS sierra 10.12.4
graalvm 0.21

steps:
- [ ] Curl -O http://download.oracle.com/otn/utilities_drivers/oracle-labs/graalvm-0.21-macosx-amd64-jdk8.tar.gz
- [ ] tar -xzvf graalvm-0.21-macosx-amd64-jdk8.tar.gz
- [ ] rvm get head
- [ ] rvm mount ~/Downloads/graalvm-0.21/language/ruby -n truffleruby
  ```
  Mounting 'ext-truffleruby' from '/Users/sharevari/Downloads/graalvm-0.21/language/ruby' with 
  'bin/ruby'
  ext-truffleruby - #gemset created /Users/sharevari/.rvm/gems/ext-truffleruby@global
  ext-truffleruby - #importing gemset 
  /Users/sharevari/.rvm/gemsets/global.gems.....................................
  ext-truffleruby - #generating global wrappers.........
  ext-truffleruby - #gemset created /Users/sharevari/.rvm/gems/ext-truffleruby
  ext-truffleruby - #importing gemsetfile /Users/sharevari/.rvm/gemsets/default.gems evaluated to 
  empty gem list
  ext-truffleruby - #generating default wrappers.........
  Empty path passed to certificates update, functions stack: 
  requirements_osx_update_openssl_cert_run rvm_requiremnts_fail_or_run_action 
  __rvm_osx_ssl_certs_ensure_for_ruby __rvm_osx_ssl_certs_ensure_for_ruby_except_jruby 
  external_mount external_mount_uniq main
  ```
- [ ] rvm ls

  ```
  rvm rubies

     ext-truffleruby [ x86_64 ]
  ```
- [ ] rvm use ext-truffleruby
  ```
  Using /Users/sharevari/.rvm/gems/ext-truffleruby
  ```
- [ ] ruby -v

  ```
  truffleruby 0.SNAPSHOT, like ruby 2.3.3 <Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13 with Graal> [darwin-x86_64]
  ```
- [ ] gem list

  ```
  [ruby] WARN A nonstandard GEM_HOME is set /Users/sharevari/.rvm/gems/ext-truffleruby
  [ruby] WARN The bad GEM_HOME may come from a ruby manager, make sure you've called one of: `rvm use system`, `rbenv system`, or `chruby system` to clear the environment.
  Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
  Error loading RubyGems plugin "/Users/sharevari/.rvm/gems/ext-truffleruby@global/gems/gem-wrappers-1.2.7/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
  [ruby] PATCH applying rubygems/request
  [ruby] PATCH applying openssl-stubs
  Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
  [ruby] PATCH applying rubygems/remote_fetcher

  *** LOCAL GEMS ***

  bigdecimal (1.2.8)
  did_you_mean (1.0.0)
  gem-wrappers (1.2.7)
  json (1.8.3)
  minitest (5.8.5)
  net-telnet (0.1.1)
  power_assert (0.2.6)
  psych (2.1.0)
  rake (10.4.2)
  rdoc (4.2.1)
  rvm (1.11.3.9)
  test-unit (3.1.5)
  ```
- [ ] gem install bundler --version 1.13.7

  ```
  [ruby] WARN A nonstandard GEM_HOME is set /Users/sharevari/.rvm/gems/ext-truffleruby
  [ruby] WARN The bad GEM_HOME may come from a ruby manager, make sure you've called one of: `rvm use system`, `rbenv system`, or `chruby system` to clear the environment.
  Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
  Error loading RubyGems plugin "/Users/sharevari/.rvm/gems/ext-truffleruby@global/gems/gem-wrappers-1.2.7/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
  Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
  [ruby] PATCH applying rubygems/package
  [ruby] PATCH applying rubygems/ext
  [ruby] PATCH applying rubygems/request
  [ruby] PATCH applying openssl-stubs
  [ruby] PATCH applying rubygems/remote_fetcher
  ERROR:  While executing gem ... (Errno::ENOENT)
      No such file or directory
  ```

Please help with installing gems,
Regards

**Comment by bjfish** [comment] 2017-03-14 21:30
This is a guess: I've seen issues with the global gemset before.  What I did was empty my global gems before mounting
 `"> ~/.rvm/gemsets/global.gems"`

**Comment by Fudoshiki** [comment] 2017-03-14 21:46
@bjfish thank you for response. but this don't work

**Comment by Fudoshiki** [comment] 2017-03-15 04:10
same result without rvm

- rvm use system
- unset GEM_HOME GEM_PATH GEM_ROOT
- ~/Downloads/graalvm-0.21/language/ruby/bin/ruby -S gem install bundler --version 1.13.7

  ```
  Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
  Error loading RubyGems plugin "/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/gems/gem-wrappers-1.2.7/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
  Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
  [ruby] PATCH applying rubygems/package
  [ruby] PATCH applying rubygems/ext
  [ruby] PATCH applying rubygems/request
  [ruby] PATCH applying openssl-stubs
  [ruby] PATCH applying rubygems/remote_fetcher
  ERROR:  While executing gem ... (Errno::ENOENT)
      No such file or directory
  ```

**Comment by eregon** [comment] 2017-03-15 12:20
@Fudoshiki You could try uninstalling the `rvm` and `gem-wrappers` gems, which are non-standard. It's probably easier to start with a fresh copy of GraalVM, and do the:
```
rvm use system
unset GEM_HOME GEM_PATH GEM_ROOT
```

**Comment by Fudoshiki** [comment] 2017-03-15 12:55
@eregon can u write steps for start please? I have rails project, want run bundle and rails s,
Regards

**Comment by Fudoshiki** [comment] 2017-03-16 04:14
on clean macOS where rvm was not installed
 
~/Downloads/graalvm-0.21/language/ruby/bin/ruby -S gem install bundler --version 1.13.7
  ```
  [ruby] PATCH applying rubygems/package
  [ruby] PATCH applying rubygems/ext
  [ruby] PATCH applying rubygems/request
  [ruby] PATCH applying openssl-stubs
  [ruby] PATCH applying rubygems/remote_fetcher
  ERROR:  While executing gem ... (Errno::ENOENT)
      No such file or directory
  ```

same

~/Downloads/graalvm-0.21/language/ruby/bin/gem install bundler --version 1.13.7

**Comment by pitr-ch** [comment] 2017-03-16 09:30
@Fudoshiki I could not reproduce the problem locally. Could you run the command with --verbose that might give more information.

**Comment by Fudoshiki** [comment] 2017-03-16 10:28
$ ~/Downloads/graalvm-0.21/language/ruby/bin/ruby -S gem install bundler --version 1.13.7 --debug

```
NOTE:  Debugging mode prints all exceptions even when rescued
Exception: `LoadError' /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require' - cannot load such file -- openssl.so
Exception: `LoadError' /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require' - cannot load such file -- openssl.so
[ruby] PATCH applying rubygems/package
Exception: `LoadError' /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require' - cannot load such file -- etc.so
[ruby] PATCH applying rubygems/ext
[ruby] PATCH applying rubygems/request
[ruby] PATCH applying openssl-stubs
Exception: `LoadError' /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require' - cannot load such file -- cgi/escape
Exception: `LoadError' /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/resolv.rb:171:in `Hosts' - LoadError
[ruby] PATCH applying rubygems/remote_fetcher
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/patches/rubygems/remote_fetcher.rb:84:in `spawn'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/patches/rubygems/remote_fetcher.rb:84:in `spawn'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/patches/rubygems/remote_fetcher.rb:84:in `spawn'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/patches/rubygems/remote_fetcher.rb:84:in `popen'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/patches/rubygems/remote_fetcher.rb:84:in ``'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/patches/rubygems/remote_fetcher.rb:84:in `download'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/source.rb:211:in `download'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/resolver/specification.rb:91:in `install'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/request_set.rb:166:in `block in install'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/request_set.rb:156:in `each'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/request_set.rb:156:in `install'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/commands/install_command.rb:250:in `install_gem'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/commands/install_command.rb:300:in `block in install_gems'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/commands/install_command.rb:296:in `each'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/commands/install_command.rb:296:in `install_gems'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/commands/install_command.rb:203:in `execute'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/command.rb:308:in `invoke_with_build_args'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/command_manager.rb:169:in `process_args'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/command_manager.rb:139:in `run'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/gem_runner.rb:55:in `run'
	/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/bin/gem:20:in `<main>'
	(core):1:in `load'
	resource:/truffleruby/core/kernel.rb:326:in `load'
	resource:/truffleruby/core/truffle/boot.rb:16:in `main_s'
Exception: `Gem::SystemExitException' /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/rubygems/user_interaction.rb:390:in `terminate_interaction' - Exiting RubyGems with exit_code 1
Exception: `SystemExit' /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/bin/gem:22:in `exit' - SystemExit
```

**Comment by pitr-ch** [comment] 2017-03-16 10:31
@Fudoshiki do you have wget installed on your system?

**Comment by Fudoshiki** [comment] 2017-03-16 10:32
brew install wget fixed this

**Comment by pitr-ch** [comment] 2017-03-16 10:35
Thanks for reporting, I'll add the requirement to the documentation and I'll add a better error message.

**Comment by Fudoshiki** [comment] 2017-03-16 10:36
Big thanks for your work. I hope that soon it will be possible to use in real applications

**Comment by Fudoshiki** [comment] 2017-03-16 12:37
thank you, can u help please with it 
```
WORKAROUND: Skipping build extension:ext/puma_http11/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/bundler/gems/extensions/x86_64-darwin/2.3.0/puma-604885b1fe2b. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
```

TRUFFLERUBY_CEXT_ENABLED=1 ~/Downloads/graalvm-0.21/language/ruby/bin/ruby -S bundle
export TRUFFLERUBY_CEXT_ENABLED=1

don't work

**Comment by pitr-ch** [comment] 2017-03-16 13:28
`TRUFFLERUBY_CEXT_ENABLED` is really intended only for us, to have a way to enable it and experiment. It's not expected to work for users. Cexts are still being implemented. Only pure Ruby is needed to try TruffleRuby at the moment.

**Comment by Fudoshiki** [comment] 2017-03-16 13:48
Thank you very much, I got to run bundle

some errors in process

```
$ ~/Downloads/graalvm-0.21/language/ruby/bin/ruby -S bundle
[ruby] PATCH applying rubygems/request
[ruby] PATCH applying openssl-stubs
[ruby] PATCH applying rubygems/remote_fetcher
[ruby] PATCH applying bundler/current_ruby
[ruby] PATCH applying bundler/dependency
[ruby] PATCH applying bundler/ruby_version
[ruby] PATCH applying rubygems/ext
[ruby] PATCH applying bundler/fetcher/downloader
[ruby] PATCH applying bundler/vendor/compact_index_client/lib/compact_index_client
[ruby] PATCH applying rubygems/package
Fetching https://github.com/rails/rails.git
Fetching https://github.com/puma/puma.git
Fetching https://github.com/sass/sassc-rails.git
Fetching https://github.com/rails/sprockets.git
Fetching https://github.com/aaronjensen/sprockets-media_query_combiner.git
Fetching https://github.com/rails/coffee-rails.git
Fetching https://github.com/rails/jquery-rails
Fetching https://github.com/Sharevari-Inc/turbolinks-rails.git
Fetching https://github.com/Sharevari-Inc/turbolinks-source-gem.git
Fetching https://github.com/nesquena/backburner.git
Fetching https://github.com/markevans/dragonfly.git
Fetching https://github.com/minimagick/minimagick.git
Fetching https://github.com/ruby-concurrency/concurrent-ruby.git
Fetching https://github.com/igrigorik/em-synchrony.git
Fetching https://github.com/ohler55/oj.git
Fetching https://github.com/mongodb/bson-ruby.git
[bson] Warning: No private key present, creating unsigned gem.
Fetching https://github.com/mongodb/mongo-ruby-driver.git
[mongo] Warning: No private key present, creating unsigned gem.
Fetching https://github.com/Sharevari-Inc/mongoid.git
[mongoid] Warning: No private key present, creating unsigned gem.
Fetching https://github.com/mongoid/mongoid-slug.git
Fetching https://github.com/simi/mongoid_paranoia.git
Fetching https://github.com/mongoid/mongoid-observers.git
Fetching https://github.com/rails/rails-observers.git
Fetching https://github.com/amatsuda/kaminari.git
Fetching https://github.com/stefanpenner/country_select.git
Fetching https://github.com/slim-template/slim.git
Fetching https://github.com/plataformatec/devise.git
Fetching https://github.com/intridea/hashie.git
Fetching https://github.com/mkdynamic/omniauth-facebook.git
Fetching https://github.com/zquestz/omniauth-google-oauth2.git
Fetching https://github.com/rails/web-console.git
Fetching https://github.com/seuros/capistrano-puma.git
Fetching https://github.com/bbatsov/rubocop.git
Fetching https://github.com/troessner/reek.git
Fetching https://github.com/sds/slim-lint.git
Fetching gem metadata from https://rubygems.org/......
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies................................................................................................................................................................................................................................................................................................................
Using rake 12.0.0
Using concurrent-ruby 1.0.5 from https://github.com/ruby-concurrency/concurrent-ruby.git (at master@54960a6)
Using minitest 5.10.1
Using i18n 0.8.1
Using bson 4.2.1 from https://github.com/mongodb/bson-ruby.git (at master@4df7982)
Using bundler 1.13.7
Using cancancan 1.16.0
Using puma 3.8.0 from https://github.com/puma/puma.git (at master@604885b)
WORKAROUND: Skipping build extension:ext/bson/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/bundler/gems/extensions/x86_64-darwin/2.3.0/bson-ruby-4df7982cd3ff. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Installing bcrypt 3.1.11 with native extensions
WORKAROUND: Skipping build extension:ext/mri/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/bcrypt-3.1.11. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Using ffi 1.9.18
WORKAROUND: Skipping build extension:ext/puma_http11/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/bundler/gems/extensions/x86_64-darwin/2.3.0/puma-604885b1fe2b. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Using chronic 0.10.2
Using rubyzip 1.2.1
Using equalizer 0.0.11
Using coderay 1.1.1
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using method_source 0.8.2
Using thor 0.19.4
Using colorize 0.8.1
Using i18n_data 0.7.0
Using sixarm_ruby_unaccent 1.1.1
Using unicode_utils 1.4.0
Using dalli 2.7.6
Using debug_inspector 0.0.2
Using orm_adapter 0.5.0
Installing unf_ext 0.0.7.2 with native extensions
WORKAROUND: Skipping build extension:ext/unf_ext/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/unf_ext-0.0.7.2. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Installing eventmachine 1.2.3 with native extensions
WORKAROUND: Skipping build extension:ext/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/eventmachine-1.2.3. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Installing http_parser.rb 0.6.0 with native extensions
WORKAROUND: Skipping build extension:ext/ruby_http_parser/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/http_parser.rb-0.6.0. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Using multipart-post 2.0.0
Installing fast_blank 1.0.0 with native extensions
WORKAROUND: Skipping build extension:ext/fast_blank/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/fast_blank-1.0.0. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Using sexp_processor 4.8.0
Using formatador 0.2.5
Installing json 2.0.3 with native extensions
WORKAROUND: Skipping build extension:ext/json/ext/generator/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/json-2.0.3. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Installing netrc 0.11.0
Installing trollop 2.1.2
Installing rb-fsevent 0.9.8
Installing ruby_dep 1.5.0
Installing lumberjack 1.0.11
Installing nenv 0.3.0
Installing shellany 0.0.1
Installing slop 3.6.0
Installing guard-compat 1.2.1
Using hashie 3.5.6 from https://github.com/intridea/hashie.git (at master@9f965fe)
Using mini_magick 4.6.1 from https://github.com/minimagick/minimagick.git (at master@d329157)
Using kaminari-core 1.0.1 from https://github.com/amatsuda/kaminari.git (at master@1c9ec36)
Using oj 2.18.3 from https://github.com/ohler55/oj.git (at master@615856a)
WORKAROUND: Skipping build extension:ext/oj/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/bundler/gems/extensions/x86_64-darwin/2.3.0/oj-615856a3891d. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
Using turbolinks-source 5.0.0 from https://github.com/Sharevari-Inc/turbolinks-source-gem.git (at master@2fc16ac)
Zlib::DataError: invalid stored block lengths
An error occurred while installing thread_safe (0.3.6), and Bundler cannot continue.
Make sure that `gem install thread_safe -v '0.3.6'` succeeds before bundling.

Zlib::DataError: invalid bit length repeat
An error occurred while installing builder (3.2.3), and Bundler cannot continue.
Make sure that `gem install builder -v '3.2.3'` succeeds before bundling.

Zlib::DataError: invalid stored block lengths
An error occurred while installing erubi (1.6.0), and Bundler cannot continue.
Make sure that `gem install erubi -v '1.6.0'` succeeds before bundling.

Zlib::DataError: invalid code lengths set
An error occurred while installing mini_portile2 (2.1.0), and Bundler cannot continue.
Make sure that `gem install mini_portile2 -v '2.1.0'` succeeds before bundling.

Zlib::DataError: invalid stored block lengths
An error occurred while installing rack (2.0.1), and Bundler cannot continue.
Make sure that `gem install rack -v '2.0.1'` succeeds before bundling.

Zlib::DataError: invalid bit length repeat
An error occurred while installing nio4r (2.0.0), and Bundler cannot continue.
Make sure that `gem install nio4r -v '2.0.0'` succeeds before bundling.

Zlib::DataError: invalid bit length repeat
An error occurred while installing mime-types-data (3.2016.0521), and Bundler cannot continue.
Make sure that `gem install mime-types-data -v '3.2016.0521'` succeeds before bundling.
```

then 

```
$ ~/Downloads/graalvm-0.21/language/ruby/bin/ruby -S gem install thread_safe -v '0.3.6'
[ruby] PATCH applying rubygems/package
[ruby] PATCH applying rubygems/ext
[ruby] PATCH applying rubygems/request
[ruby] PATCH applying openssl-stubs
[ruby] PATCH applying rubygems/remote_fetcher
Successfully installed thread_safe-0.3.6
1 gem installed
```

and bundle again

I stopped on nio4r
```
$ ~/Downloads/graalvm-0.21/language/ruby/bin/ruby -S gem install nio4r -v '2.0.0'
[ruby] PATCH applying rubygems/package
[ruby] PATCH applying rubygems/ext
[ruby] PATCH applying rubygems/request
[ruby] PATCH applying openssl-stubs
[ruby] PATCH applying rubygems/remote_fetcher
Building native extensions.  This could take a while...
WORKAROUND: Skipping build extension:ext/nio4r/extconf.rb, dest_path:/Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/nio4r-2.0.0. Set environment variable TRUFFLERUBY_CEXT_ENABLED to build the extensions.
ERROR:  Error installing nio4r:
	ERROR: Failed to build gem native extension.

    current directory: /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/gems/nio4r-2.0.0/ext/nio4r
/Users/sharevari/Downloads/graalvm-0.21/language/ruby/bin/truffleruby -r ./siteconf20170316-31781-axy7z3.rb extconf.rb
checking for unistd.h... /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:469:in `try_do': The compiler failed to generate an executable file.
You have to install development tools first.
 (RuntimeError)
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:600:in `try_cpp'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:1104:in `block in have_header'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:955:in `block in checking_for'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:363:in `block (2 levels) in postpone'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:333:in `open'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:363:in `block in postpone'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:333:in `open'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:359:in `postpone'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:954:in `checking_for'
	from /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/mri/mkmf.rb:1103:in `have_header'
	from extconf.rb:5:in `<main>'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/sharevari/Downloads/graalvm-0.21/language/ruby/bin/truffleruby

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/nio4r-2.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/gems/nio4r-2.0.0 for inspection.
Results logged to /Users/sharevari/Downloads/graalvm-0.21/language/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-darwin/2.3.0/nio4r-2.0.0/gem_make.out
```

Yet not all the gems are put, but thank you very much and I'll be able to test more with more

**Comment by pitr-ch** [comment] 2017-03-16 17:50
You are welcome. This looks like a big application I would not expect it to work even if it installed, most of the gems do not include pure ruby implementation of their C extension parts.

**Comment by eregon** [comment] 2017-08-01 15:25
I'll close this as it's been a while and we can now run Bundler without any special setup.
We can also compile a few basic C extensions but this is early days and work in progress.

**Closed by eregon** 2017-08-01 15:25 UTC
Labels: question
